{
    'name': 'POS: Product Profitability and Margin Report',
    'version': '17.0.1.0.0',
    'summary': 'Sales margin Report',
    'description': """ Sales Margin""",
    'category': 'pos',
    'author': 'Biniyam k',
    'website': 'mailto:biniyamkg@gmail.com',
    'license': 'LGPL-3',
    'price': '20.0',
    'currency': 'USD',
    'depends': ['point_of_sale', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'report/bk_margin_report.xml',
        'wizard/bk_pos_profit_report_wizard_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}
